UEECnotes/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 命名空间
    path('', include(('forums.urls', 'forums'), namespace="forums")),
    path('', include(('authentication.urls', 'authentication'), namespace="authentication")),
    path('', include(('game.urls', 'game'), namespace="game")),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace="userprofile")),
]

authentication/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
]

forums/urls.py
from django.urls import path
from forums.views import *
from .views import PostList

urlpatterns = [
    path('forums/', forums, name='forums'),
    path('', welcome, name='welcome'),
    path('contact/', contact, name='contact'),
    path('ab/', ab, name="ab"),
    path('updatelog/', update_log, name='update_log'),
    path('api/posts/', PostList.as_view()),
]

game/urls.py
from django.urls import path
from game.views import *

urlpatterns = [
    path('game/', game, name='game'),


]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.

class MyUser(AbstractUser):
    B2024 = 2023
    Y2024 = 2024
    Y2025 = 2025
    Y2026 = 2026
    A2026 = 2027
    TERM1 = 1
    TERM2 = 2
    TERM3 = 3
    YEAR_CHOICES = [
        (B2024, 'before 2024'),
        (Y2024, '2024'),
        (Y2025, '2025'),
        (Y2026, '2026'),
        (A2026, 'after 2026'),
    ]
    TERM_CHOICES = [
        (TERM1, '1'),
        (TERM2, '2'),
        (TERM3, '3'),
    ]
    admission_year = models.IntegerField(choices=YEAR_CHOICES, null=True)
    admission_term = models.IntegerField(choices=TERM_CHOICES, null=True)
    future_major = models.CharField(max_length=100, null=True)

authentication/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from . tokens import generate_token

from UEECnotes import settings

# Create your views here.
def home(request):
    if not request.user.is_authenticated:
        messages.error(request, "Please SignIn")
    return render(request, "authentication/home.html")


def signup(request):
    if request.method == "POST":
        username = request.POST.get('username')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password_conf = request.POST.get('password_conf')
          
        user_isActive = User.objects.filter(username=username).first()
        if user_isActive:
            if user_isActive.is_active:
                messages.error(request, "username already exist! Please try some other username")
                return redirect('authentication:signup')
            else:
                user_isActive.delete()

        email_isActive = User.objects.filter(email=email).first()
        if email_isActive:
            if email_isActive.is_active:
                messages.error(request, "username already registered!")
                return redirect('authentication:signup')
            else:
                email_isActive.delete()

        if len(username) > 10:
            messages.error(request, "Username must be under 10 characters")
            return redirect('authentication:signup')

        if password != password_conf:
            messages.error(request, "Passwords didn't match")
            return redirect('authentication:signup')

        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric!")
            return redirect('authentication:signup')

        my_user = User.objects.create_user(username, email, password)
        my_user.first_name = fname
        my_user.last_name = lname
        my_user.is_active = False
        my_user.save()

        messages.success(request, "Your Account has been successfully created. We have sent you a confirmation email, please confirm your email address in order to activate account.")

        # welcome Email
        subject = "Welcome to UEECnotes!!"
        message = " Hello " +\
                  my_user.first_name +\
                  "!! \n" +\
                  " Welcome to UEECnotes!! \n" \
                  " Thank you for visiting our website \n" \
                  " We have also sent you a confirmation email, please confirm your email address in order to activate account. \n\n" \
                  " Thanking you \n" \
                  " 招募前端开发、后端开发、内容创作团队成员\n"\
                  " Yang"
        from_email = settings.EMAIL_HOST_USER
        to_list = [my_user.email]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        # Email Address Confirmation Email

        current_site = get_current_site(request)
        email_subject = "Confirm your email @ UEECnotes"
        message2 = render_to_string('authentication/email_confirmation.html', {
            'name': my_user.first_name,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(my_user.pk)),
            'token': generate_token.make_token(my_user)
        })
        email = EmailMessage(
            email_subject,
            message2,
            settings.EMAIL_HOST_USER,
            [my_user.email],
        )
        email.fail_silently = True
        # there should be error handling.
        email.send()
        # sign up successfully
        return redirect('forums:welcome')

    return render(request, "authentication/signup.html")


def signin(request):

    if request.method == "POST":
        # it is similar to request.POST.get('username')
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        # sign in successfully
        if user is not None:
            login(request, user)
            fname = user.first_name
            return render(request, "forums/welcome.html", {'fname': fname})

        else:
            messages.error(request, "Invalid username or password. If you have already registered, please confirm your confirmation email")
            return redirect('authentication:signin')

    return render(request, "authentication/signin.html")


def signout(request):
    logout(request)
    messages.success(request, "Logged Out Successfully!")
    return redirect('authentication:home')

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        login(request, myuser)
        return redirect('forums:welcome')
    else:
        return render(request, 'authentication/activate_failed.html')

authentication/templates/authentication/activate_failed.html
{% autoescape off %}
    Activation failed, please try again!
{% endautoescape %}

authentication/templates/authentication/email_confirmation.html
{% autoescape off %}
    Welcome to UEECnotes

    Hello {{ name }}

    Please confirm your email by clicking on the following link.

    Confirmation Link: http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}

{% endautoescape %}

authentication/templates/authentication/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authentication</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/css/home.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'authentication/css/modal.css' %}?v=1">
</head>
<body>
<div class="home_body">
{% for message in messages %}
    <div class="hidden-message" style="display: none;" data-message="{{ message }}">
        {{ message }}
    </div>
{% endfor %}

<!-- 弹窗结构 -->
<div id="messageModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close-button">&times;</span>
        <p id="modal-message"></p>
    </div>
</div>


    <div class="home_shell">
    <h6 class="home_title">Welcome to UEECnotes</h6>
    <button type="submit"><a href="{% url "authentication:signup" %}">SignUp(注册)</a></button>
    <button type="submit"><a href="{% url "authentication:signin" %}">SignIn(登录)</a></button>
    <button type="submit"><a href="{% url "authentication:signout" %}">SignOut(登出)</a></button>
    <button type="submit"><a href="{% url "forums:welcome" %}">Go to Main Page</a></button>
    </div>
    </div>
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>#}
<script src="{% static 'authentication/js/modalMessage.js' %}"></script>
</body>
</html>

authentication/templates/authentication/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

authentication/templates/authentication/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/css/signin.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'authentication/css/modal.css' %}?v=1">
</head>
<body>
{% for message in messages %}
    <div class="hidden-message" style="display: none;" data-message="{{ message }}">
        {{ message }}
    </div>
{% endfor %}
<div id="messageModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close-button">&times;</span>
        <p id="modal-message"></p>
    </div>
</div>

    <div class="signin_body">
    <div class="signin_shell">
<h3 class="signin_title">SignIn</h3>

    <form action="/signin/" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" id="username" name="username" placeholder="">
        <br>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="">
        <br>
        <button type="submit">Sign In</button>
    </form>
         <div style="display: flex;width:100%;justify-content: space-between">

        <a href="{% url "authentication:signup" %}">Go to register!(去注册)</a>
        <a href="{% url "authentication:home" %}">goBack(回主页)</a>
         </div>
</div>
</div>
    <script src="{% static 'authentication/js/modalMessage.js' %}"></script>

</body>
</html>

authentication/templates/authentication/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication/css/signup.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'authentication/css/modal.css' %}?v=1">
</head>
<body>


{% for message in messages %}
    <div class="hidden-message" style="display: none;" data-message="{{ message }}">
        {{ message }}
    </div>
{% endfor %}
<div id="messageModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close-button">&times;</span>
        <p id="modal-message"></p>
    </div>
</div>
<div class="signup_body">
    <div class="signup_shell">
<h3 class="signup_title">SignUp</h3>
    <form action="/signup/" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" id="username" name="username" placeholder="Create a username(Only letters and numbers)">
        <br>
        <label for="fname">First Name</label>
        <input type="text" id="fname" name="fname" placeholder="Enter Your First Name">
        <br>
        <label for="lname">Last Name</label>
        <input type="text" id="lname" name="lname" placeholder="Enter Your Last Name">
        <br>
        <label for="email">Email Address</label>
        <input type="email" id="email" name="email" placeholder="Enter Your Email Address">
        <br>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="Create a Password">
        <br>
        <label for="password_conf">Confirm your password</label>
        <input type="password" id="password_conf" name="password_conf" placeholder="Confirm Your Password">

        <button type="submit">Sign up</button>
    </form>
    <div style="display: flex;width:100%;justify-content: space-between">
    <a href="{% url "authentication:signin" %}">signIn(去登录)</a>
    <a href="{% url 'authentication:home' %}">goBack(回主页)</a>
    </div>
    </div>
 </div>

    <script src="{% static 'authentication/js/modalMessage.js' %}"></script>

</body>
</html>