UEECnotes/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 命名空间
    path('', include(('forums.urls', 'forums'), namespace="forums")),
    path('', include(('authentication.urls', 'authentication'), namespace="authentication")),
    path('', include(('game.urls', 'game'), namespace="game")),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace="userprofile")),
]

authentication/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
]

forums/urls.py
from django.urls import path
from forums.views import *
from .views import PostList

urlpatterns = [
    path('forums/', forums, name='forums'),
    path('', welcome, name='welcome'),
    path('contact/', contact, name='contact'),
    path('ab/', ab, name="ab"),
    path('updatelog/', update_log, name='update_log'),
    path('api/posts/', PostList.as_view()),
]

game/urls.py
from django.urls import path
from game.views import *

urlpatterns = [
    path('game/', game, name='game'),


]

userprofile/urls.py
from django.urls import path,include
from userprofile.views import *

urlpatterns = [
   path('', userprofile, name='userprofile'),
]

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel='stylesheet' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
  <link rel="stylesheet" href="{% static 'base/css/base_style.css' %}?v=3">
    {% block cssLink %}{% endblock %}
</head>
<body>
<!-- partial:index.partial.html -->
<div class="base_wrapper">
  <div class="base_sidebar">
    <div class="base_title">
        Hi! {{ fname }}
    </div>
    <ul class="nav">
      <li>
        <a  href="{% url "forums:welcome" %}" onclick="handleClick(this)">笔记</a>
      </li>
      <li>
        <a  href="{% url "forums:forums" %}" onclick="handleClick(this)">论坛（需要登录）</a>
      </li>
      <li>
        <a  href="{% url "game:game" %}" onclick="handleClick(this)">小游戏(暂时损坏)</a>
      </li>
      <li>
        <a  href="{% url "forums:contact" %}" onclick="handleClick(this)">联系我们</a>
      </li>
      <li>
        <a  href="{% url "userprofile:userprofile" %}" onclick="handleClick(this)">个人主页</a>
      </li>
      <li>
        <a href="{% url "authentication:home" %}">Home(切换账号/退出账号)</a>
      </li>
    </ul>
  </div> 
  <div class="base_content content-is-open">
    <span class='side-panel-toggle'>
      <i class="fa fa-bars"></i>
    </span>

    <div class="well well-sm">
      {% block content %}
      
      {% endblock %}
    </div>
    <hr>
 </div>
</div>
</body>
  <script src='../static/base/js/jquery.min.js'></script>
  <script src="../static/base/js/script.js?v=4"></script>
  {% block script %}
  {% endblock %}
</html>