UEECnotes/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 命名空间
    path('', include(('forums.urls', 'forums'), namespace="forums")),
    path('', include(('authentication.urls', 'authentication'), namespace="authentication")),
    path('', include(('game.urls', 'game'), namespace="game")),
    path('profile/', include(('userprofile.urls', 'userprofile'), namespace="userprofile")),
]

forums/urls.py
from django.urls import path
from forums.views import *
from .views import PostList

urlpatterns = [
    path('forums/', forums, name='forums'),
    path('', welcome, name='welcome'),
    path('contact/', contact, name='contact'),
    path('ab/', ab, name="ab"),
    path('updatelog/', update_log, name='update_log'),
    path('api/posts/', PostList.as_view()),
]

game/urls.py
from django.urls import path
from game.views import *

urlpatterns = [
    path('game/', game, name='game'),


]

forums/models.py
from django.db import models

from authentication.models import MyUser


# Create your models here.
class Post(models.Model):
    post_id = models.AutoField(primary_key=True, unique=True)
    post_name = models.CharField(max_length=100)
    post_content = models.TextField()
    post_by = models.ForeignKey(MyUser, on_delete=models.SET_NULL, null=True)
    post_by_name = models.CharField(max_length=100, null=True)

    def __str__(self):
       return f'post_name: {self.post_name}'

forums/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,HttpResponse
from .models import Post
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import PostSerializer

class PostList(APIView):
    def get(self, request):
        posts = Post.objects.all()
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@login_required(login_url='/home/')
def forums(request):
    fname = request.user.first_name
    user_id = request.user.id
    if request.method == 'POST':
        # 处理表单提交

        title = request.POST.get('post-title')
        content = request.POST.get('post-content')

        # 创建并保存新的Post对象
        Post.objects.create(
            post_name = title, 
            post_content = content, 
            post_by_id = user_id, 
            post_by_name = fname)

        # 可以根据需要重定向到成功页面或其他页面
        return redirect("forums:forums")
    if request.method == "GET":
        posts = Post.objects.all()
        return render(request, 'forums/forums.html', {'posts': posts, 'fname': fname})



def welcome(request):
    # print(request.user.is_authenticated)
    if request.user.is_authenticated:
        # 安全地访问 first_name，因为用户已登录
        fname = request.user.first_name
    else:
        # 处理未登录用户的情况
        # 例如，你可以设置一个默认的名字，或者直接跳过某些操作
        fname = "游客"
    return render(request, 'forums/welcome.html', {"fname": fname})


@login_required(login_url='/home/')
def contact(request):
    fname = request.user.first_name
    return render(request, 'forums/contact.html', {"fname": fname})


def update_log(request):
    return render(request, 'forums/update_log.html')


@login_required(login_url='/home/')
def ab(request):
    fname = request.user.first_name
    return render(request, 'notes/ab.html', {"fname": fname})

forums/templates/forums/contact.html
{% extends "base.html" %}
{% block title %}contact{% endblock %}
{% block content %}


<main>
<div style="font-size: 30px">
<div>
    欢迎优秀的内容创作者
</div>
<div>欢迎前端开发人员</div>
<div>欢迎后端开发人员</div>
<div>
    联系QQ:1837827317
</div>
</div>
 </main>

{% endblock %}

forums/templates/forums/forums.html
{% extends "base.html" %}
{% load static %}
{% block title %}论坛{% endblock %}
{% block cssLink %}
  <link rel="stylesheet" href="{% static 'forums/css/styles.css' %}?v=1">
{% endblock %}
{% block content %}
    <main>
        <section id="post-list">
            <h2>Posts</h2>
            <div class="post">
                {% for post in posts %}
                    <h3>{{ post.post_name }}</h3>
                      <p>{{ post.post_content }}---created by {{post.post_by_name}}</p>
                    <hr>
                {% endfor %}
            </div>

        </section>
        <section id="create-post">
            <h2>Create Post</h2>
            <form id="post-form" method="post">
                {% csrf_token %}
                <input type="text" name="post-title" placeholder="Title" >
                <textarea name="post-content" placeholder="Write your post here..." ></textarea>
                <button type="submit">Submit Post</button>
            </form>
        </section>
        <section id="comments">
            <h2>Comments</h2>
            <!-- Comments will be listed here -->
        </section>
    </main>
{% endblock %}

forums/templates/forums/snake.html
{% extends "base.html" %}
{% block title %}小游戏{% endblock %}
{% block content %}
    <div class="mf"></div>
    <div>使用‘W’\‘S’\‘A’\‘D’进行游戏</div>
    <button onclick="refreshPage()">重新开始</button>

    <script>

        function refreshPage() {
            // 使用 location.reload() 方法刷新页面
            location.reload();
        }

        const rows = 20
        const cols = 20
        const size = 20
        const mf = document.querySelector('.mf')
        const result = []
        const player = [
            [1, 1]
        ]
        const updatePlayer = () => {
            document.querySelectorAll('.player').forEach(v => v.classList.remove('player'))
            player.forEach(v => {
                document.querySelector(`[data-v="${v.join('-')}"]`).classList.add('player')
            })
        }
        let key = ''
        for(let i=0;i<rows;i++) {
            for(let j=0;j<cols;j++) {
                const isEat = Math.random() > 0.9
                result.push(`<div data-v="${i}-${j}" class="item ${isEat ? 'eat': ''}" style="width:${size}px;height:${size}px"></div>`)
            }
        }
        mf.innerHTML = result.join('')
        mf.style.width = `${cols * size}px`
        document.addEventListener('keydown', e=> {
            if(e.key.match(/^w|a|s|d$/)) {
                key = e.key
            }
        })
        const intervalId = setInterval(() => {
            if (key) {
                const needPos = JSON.parse(JSON.stringify(player.slice(0, player.length - 1)))
                switch(key) {
                    case 'w':
                        player[0][0] -= 1
                        break;
                    case 'a':
                        player[0][1] -= 1
                        break;
                    case 's':
                        player[0][0] += 1
                        break;
                    case 'd':
                        player[0][1] += 1
                        break;
                }
                const el = document.querySelector(`[data-v="${player[0].join('-')}"]`)
                if (!el) {
                    clearInterval(intervalId)
                    alert('撞墙了')
                } else {
                    for (let i=1;i<player.length;i++) {
                        player[i] = needPos[i - 1]
                    }
                    if (el.className.indexOf('eat') >= 0) {
                        el.classList.remove('eat')
                        player.push([...player[0]])
                    }
                    updatePlayer()
                }
            }
        }, 100)
        updatePlayer()
    </script>
{% endblock %}

forums/templates/forums/update_log.html
{% extends "base.html" %}
{% load static %}
{% block title %}笔记{% endblock %}
{% block cssLink %}
  <link rel="stylesheet" href="{% static 'forums/css/update_log.css' %}?v=5">
   <link rel="stylesheet" href="https://static.fontawesome.com/css/fontawesome-app.css">
    <!-- 引入字体 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400&display=swap">
{% endblock %}
{% block content %}
<div class="log_body">
   <div class="log_shell">
        <div class="shell_body">
            <div class="log_button">
                <div class="prev"><i class="iconfont icon-backward_filled"></i></div>
                <div class="next"><i class="iconfont icon-forward_filled"></i></div>
            </div>
            <div class="shell_slider">
                <div class="log_item">
                    <div class="log_frame">
                        <div class="log_box front">
                            <h1>2023.12.19</h1>
                            <span>
                                1、增加了用户登录系统
                                2、更新了日志UI
                                3、更新了小游戏
                            </span>
                        </div>
                        <div class="log_box left"></div>
                        <div class="log_box right"> </div>
                    </div>
                </div>
                <div class="log_item">
                    <div class="log_frame">
                        <div class="log_box front">
                            <h1>2023.12.14</h1>
                            <span>
                                1、添加了小游戏分区（但css损坏）
                                2、更新了UI，导航栏可以收回了
                            </span>
                        </div>
                        <div class="log_box left"></div>
                        <div class="log_box right"> </div>
                    </div>
                </div>
                <div class="log_item">
                    <div class="log_frame">
                        <div class="log_box front">
                            <h1>2023.12.13</h1>
                            <span>
                                1、站点由note.yang3457.com改为ueec.yang3457.com
                                2、架构由PHP改为Django
                                3、增加论坛灌水区
                            </span>
                        </div>
                        <div class="log_box left"></div>
                        <div class="log_box right"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    // 获取所有的item元素
    var items = document.getElementsByClassName('log_item');
    // 循环遍历每个item
    for (var i = 0; i < items.length; i++) {
        // 获取当前item
        var item = items[i];
        var frame = item.getElementsByClassName('log_frame')[0];
        var frontBox = frame.getElementsByClassName('front')[0];
        var leftBox = frame.getElementsByClassName('left')[0];
        var rightBox = frame.getElementsByClassName('right')[0];
        // 设置背景图片
        frontBox.style.backgroundImage = 'url(../../static/forums/img/' + (i + 1).toString().padStart(2, '0') + '.jpg)';
        leftBox.style.backgroundImage = 'url(../../static/forums/img/' + (i + 1).toString().padStart(2, '0') + '.jpg)';
        rightBox.style.backgroundImage = 'url(../../static/forums/img/' + (i + 1).toString().padStart(2, '0') + '.jpg)';
    }
    (function () {
        "use strict";
        var shell = document.getElementsByClassName('log_shell')[0];
        var slider = shell.getElementsByClassName('shell_slider')[0];
        var items = shell.getElementsByClassName('log_item');
        var prevBtn = shell.getElementsByClassName('prev')[0];
        var nextBtn = shell.getElementsByClassName('next')[0];
        // 定义变量
        var width, height, totalWidth, margin = 20,
            currIndex = 0,
            interval, intervalTime = 3000;
        function init() {
            // 初始化函数
            resize();
            move(Math.floor(items.length / 2));
            bindEvents();
            timer();
        }
        function resize() {
            // 窗口大小变化时调整大小
            width = Math.max(window.innerWidth * .20, 275);
            height = window.innerHeight * .5;
            totalWidth = width * items.length;
            // 设置slider宽度
            slider.style.width = totalWidth + "px";
            // 设置每个item的宽度和高度
            for (var i = 0; i < items.length; i++) {
                let item = items[i];
                item.style.width = (width - (margin * 2)) + "px";
                item.style.height = height + "px";
            }
        }
        function bindEvents() {
            // 窗口大小变化时调整大小
            window.onresize = resize;
            // 点击prev按钮切换item
            prevBtn.addEventListener('click', () => { prev(); });
            nextBtn.addEventListener('click', () => { next(); });
        }
        init();
        function move(index) {
            // 移动shell到指定的item
            if (index < 1) index = items.length;
            if (index > items.length) index = 1;
            currIndex = index;
            // 遍历所有item
            for (var i = 0; i < items.length; i++) {
                let item = items[i],
                    box = item.getElementsByClassName('log_frame')[0];
                if (i === (index - 1)) {
                    // 当前item添加active类并设置3D效果
                    item.classList.add('item--active');
                    box.style.transform = "perspective(1200px)";
                } else {
                    // 其他item移除active类并设置3D效果
                    item.classList.remove('item--active');
                    box.style.transform = "perspective(1200px) rotateY(" + (i < (index - 1) ? 40 : -40) + "deg)";
                }
            }
            // 移动slider
            slider.style.transform = "translate3d(" + ((index * -width) + (width / 2) + window.innerWidth / 2) + "px, 0, 0)";
            // 设置body背景图片
            var frontBox = items[index - 1].getElementsByClassName('front')[0];
            var wellDiv = document.querySelector('.well');
            wellDiv.style.backgroundImage = frontBox.style.backgroundImage;
        }
        function timer() {
            // 定时器，自动切换shell
            clearInterval(interval);
            interval = setInterval(() => {
                move(++currIndex);
            }, intervalTime);
        }
        // 切换item
        function prev() {
            move(--currIndex);
            timer();
        }
        function next() {
            move(++currIndex);
            timer();
        }
    })();
</script>

{% endblock %}


{#{% block script %}#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>#}
{#    <script>#}
{#        (function($){#}
{#            $.fn.timeline = function()#}
{#            {#}
{#                var selectors = {#}
{#                    id: $(this),#}
{#                    item: $(this).find(".item"),#}
{#                    activeClass: "item--active",#}
{#                    img:".img"#}
{#                };#}
{#                selectors.item.eq(0).addClass(selectors.activeClass);#}
{#                selectors.id.css(#}
{#                    "background-image",#}
{#                    "url(" +#}
{#                    selectors.item.first()#}
{#                        .find(selectors.img)#}
{#                        .attr("src") +#}
{#                    ")"#}
{#                );#}
{#                var itemLength = selectors.item.length;#}
{#                $(window).scroll(function(){#}
{#                    var max,min;#}
{#                    var pos = $(this).scrollTop();#}
{#                    selectors.item.each(function(i){#}
{#                        min = $(this).offset().top;#}
{#                        max = $(this).height() + $(this).offset().top;#}
{#                        var that = $(this);#}
{#                        if (i === itemLength -2 && pos > min + $(this).height()/2){#}
{#                            selectors.item.removeClass(selectors.activeClass);#}
{#                            selectors.id.css(#}
{#                                "background-image",#}
{#                                "url(" +#}
{#                                selectors.item.last()#}
{#                                    .find(selectors.img)#}
{#                                    .attr("src") +#}
{#                                ")"#}
{#                            );#}
{#                            selectors.item.last().addClass(selectors.activeClass);#}
{#                        }#}
{#                        else if(pos <= max - 10 && pos >= min){#}
{#                            selectors.id.css(#}
{#                                "background-image",#}
{#                                "url(" +#}
{#                                $(this)#}
{#                                .find(selectors.img)#}
{#                                .attr("src") +#}
{#                                ")"#}
{#                            );#}
{#                            selectors.item.removeClass(selectors.activeClass);#}
{#                            $(item).addClass(selectors.activeClass);#}
{#                        }#}
{#                    });#}
{#                });#}
{#            };#}
{#        })(jQuery)#}
{##}
{#        $("#shell").timeline();#}
{#    </script>#}
{#{% endblock %}#}

forums/templates/forums/welcome.html
{% extends "base.html" %}
{% block title %}笔记{% endblock %}
{% block content %}

<main>
  <h1>UEEC10 算分任务/考试攻略</h1>
    <h2>
        抄袭后果严重，本站暂仅提供杂七杂八的要求说明，让你安心做作业，用心去考试
    </h2>
    <h3>都是自己人，手下留情，请勿攻击</h3>

    <h3>（最新更新于2023年12月14日）</h3>
    <h3>
    <a href="{% url 'forums:update_log' %}">网站更新日志</a>
    </h3>
{% for message in messages %}
    <div class="alert alert-{{ message.tages }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong>{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}


{% if user.is_authenticated %}
    <div>
        <h3>Hello!{{ fname }}</h3>
        <h4>You are successfully logged in.</h4>
    </div>
{% endif %}

{#        <div>#}
{##}
{#            <a href="{% url 'app01:index' %}">跳转到index</a>#}
{#        </div>#}
    <div style="font-size: 20px;margin: 20px;" >
    <a href="https://student.unsw.edu.au/harvard-referencing">
        https://student.unsw.edu.au/harvard-referencing
    </a>
     </div>
 <div style="font-size: 20px;margin: 20px;">
    <a href="{% url 'forums:ab' %}">
        AB相关的东西
    </a>
 </div>

  <div>
      ---------discussion skills----------
  </div>
{#  <img src="/static/img/DS/DS.png">#}
  <div>

  </div>

  <div>

  </div>
{#  <img src="/static/img/DS/DS2.png">#}
</main>
{% endblock %}